semantic_pointcloud_builder:
  ros__parameters:
    fx: 535.4
    fy: 539.2
    cx: 320.1
    cy: 247.6

    rgb_topic: "/camera/rgb/image_color"
    depth_topic: "/camera/depth/image"
    mask_topic: "/semantic/combined_mask"
    pose_topic: "/orb_slam3/camera_pose"
    output_topic: "/semantic_global_map"

    sync_max_interval: 0.03
    pose_sync_tolerance: 0.05

    min_keyframe_translation: 0.03
    min_keyframe_rotation_deg: 2.0
    world_align_roll_deg: -90.0

    enable_instance_markers: false
    instance_marker_topic: "/semantic_instances_markers"
    cluster_tolerance: 0.20
    cluster_min_size: 100
    cluster_max_size: 200000
    instance_publish_every_n_frames: 60
    instance_cluster_voxel_leaf_size: 0.10
    max_points_for_instance_clustering: 40000
    excluded_labels: [0]

    max_points_per_frame: 12000

    local_voxel_leaf_size: 0.05
    voxel_leaf_size: 0.03
    depth_min: 0.1
    depth_max: 8.0
